export type DukeExampleLineup = {
  id: string;
  players: [string, string, string, string, string];
  minutes: number;
  possessions: number;
  pointsFor: number;
  pointsAgainst: number;
  fgm: number;
  fga: number;
  tpm: number;
  tpa: number;
};

export const DUKE_EXAMPLE_SEASON = "2025";
export const DUKE_EXAMPLE_TEAM = "Duke";

export const DUKE_EXAMPLE_PLAYERS = [
  "Tyrese Proctor",
  "Kon Knueppel",
  "Sion James",
  "Cooper Flagg",
  "Khaman Maluach",
  "Caleb Foster",
  "Isaiah Evans",
  "Maliq Brown",
  "Mason Gillis",
  "Patrick Ngongba II",
] as const;

export const DUKE_EXAMPLE_LINEUPS: DukeExampleLineup[] = [
  {
    id: "L1",
    players: ["Tyrese Proctor", "Kon Knueppel", "Sion James", "Cooper Flagg", "Khaman Maluach"],
    minutes: 128.4,
    possessions: 262,
    pointsFor: 326,
    pointsAgainst: 232,
    fgm: 116,
    fga: 214,
    tpm: 33,
    tpa: 86,
  },
  {
    id: "L2",
    players: ["Tyrese Proctor", "Kon Knueppel", "Cooper Flagg", "Maliq Brown", "Khaman Maluach"],
    minutes: 86.1,
    possessions: 173,
    pointsFor: 205,
    pointsAgainst: 145,
    fgm: 72,
    fga: 149,
    tpm: 19,
    tpa: 54,
  },
  {
    id: "L3",
    players: ["Tyrese Proctor", "Sion James", "Isaiah Evans", "Cooper Flagg", "Khaman Maluach"],
    minutes: 73.9,
    possessions: 149,
    pointsFor: 181,
    pointsAgainst: 148,
    fgm: 63,
    fga: 136,
    tpm: 21,
    tpa: 61,
  },
  {
    id: "L4",
    players: ["Caleb Foster", "Kon Knueppel", "Sion James", "Cooper Flagg", "Khaman Maluach"],
    minutes: 61.7,
    possessions: 121,
    pointsFor: 147,
    pointsAgainst: 108,
    fgm: 54,
    fga: 111,
    tpm: 16,
    tpa: 40,
  },
  {
    id: "L5",
    players: ["Tyrese Proctor", "Kon Knueppel", "Sion James", "Mason Gillis", "Khaman Maluach"],
    minutes: 57.3,
    possessions: 114,
    pointsFor: 128,
    pointsAgainst: 101,
    fgm: 46,
    fga: 100,
    tpm: 15,
    tpa: 44,
  },
  {
    id: "L6",
    players: ["Tyrese Proctor", "Kon Knueppel", "Isaiah Evans", "Cooper Flagg", "Maliq Brown"],
    minutes: 51.8,
    possessions: 103,
    pointsFor: 116,
    pointsAgainst: 94,
    fgm: 42,
    fga: 91,
    tpm: 14,
    tpa: 39,
  },
  {
    id: "L7",
    players: ["Caleb Foster", "Isaiah Evans", "Sion James", "Cooper Flagg", "Khaman Maluach"],
    minutes: 43.6,
    possessions: 88,
    pointsFor: 99,
    pointsAgainst: 79,
    fgm: 35,
    fga: 82,
    tpm: 13,
    tpa: 36,
  },
  {
    id: "L8",
    players: ["Tyrese Proctor", "Kon Knueppel", "Sion James", "Maliq Brown", "Patrick Ngongba II"],
    minutes: 39.2,
    possessions: 79,
    pointsFor: 85,
    pointsAgainst: 73,
    fgm: 31,
    fga: 70,
    tpm: 10,
    tpa: 28,
  },
  {
    id: "L9",
    players: ["Tyrese Proctor", "Isaiah Evans", "Sion James", "Mason Gillis", "Khaman Maluach"],
    minutes: 32.7,
    possessions: 67,
    pointsFor: 74,
    pointsAgainst: 63,
    fgm: 27,
    fga: 62,
    tpm: 9,
    tpa: 26,
  },
  {
    id: "L10",
    players: ["Caleb Foster", "Kon Knueppel", "Isaiah Evans", "Cooper Flagg", "Maliq Brown"],
    minutes: 28.4,
    possessions: 58,
    pointsFor: 66,
    pointsAgainst: 57,
    fgm: 24,
    fga: 55,
    tpm: 8,
    tpa: 23,
  },
  {
    id: "L11",
    players: ["Tyrese Proctor", "Kon Knueppel", "Mason Gillis", "Cooper Flagg", "Patrick Ngongba II"],
    minutes: 24.8,
    possessions: 49,
    pointsFor: 53,
    pointsAgainst: 46,
    fgm: 19,
    fga: 44,
    tpm: 7,
    tpa: 18,
  },
  {
    id: "L12",
    players: ["Caleb Foster", "Sion James", "Isaiah Evans", "Maliq Brown", "Khaman Maluach"],
    minutes: 22.6,
    possessions: 46,
    pointsFor: 48,
    pointsAgainst: 44,
    fgm: 17,
    fga: 43,
    tpm: 5,
    tpa: 17,
  },
  {
    id: "L13",
    players: ["Tyrese Proctor", "Kon Knueppel", "Sion James", "Cooper Flagg", "Mason Gillis"],
    minutes: 19.9,
    possessions: 40,
    pointsFor: 51,
    pointsAgainst: 34,
    fgm: 18,
    fga: 36,
    tpm: 8,
    tpa: 19,
  },
  {
    id: "L14",
    players: ["Caleb Foster", "Kon Knueppel", "Sion James", "Maliq Brown", "Patrick Ngongba II"],
    minutes: 17.3,
    possessions: 34,
    pointsFor: 36,
    pointsAgainst: 31,
    fgm: 13,
    fga: 32,
    tpm: 4,
    tpa: 13,
  },
];
